name: Go

on:
  push:
    branches: [ masta ]
  pull_request:
    branches: [ masta ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snpt-server
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Info
      run: ls
      
    - name: Install Modules
      run: go get -d 
      
    - name: Build
      run: go build -v ./main.go -o backend-artifact
    
    - name: Info
      run: ls
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: ./backend-artifact
