name: Go

on:
  push:
    branches: [ masta ]
  pull_request:
    branches: [ masta ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Install Modules
      run: go get -d ./snpt-server/
      
    - name: Build
      run: go build -v ./snpt-server/main.go
